version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  kode:
    container_name: kode-speller
    build:
      context: ./
    image: kode-speller/kode-speller:multistage
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      ADDRESS: 0.0.0.0:8080
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: kode_test
    links:
      - db
volumes:
  db:
    driver: local